name: classicpress-migration-plugin
recipe: wordpress

config:
  webroot: test/site/
  php: '7.0'

tooling:
  bash:
    service: appserver

proxy:
  appserver:
    # single site
    - test.lndo.site
    # multisite
    - one.lndo.site
    - two.lndo.site
